language: python
python:
- '3.7'
services:
- postgresql
before_script:
- psql -c 'create database greeklinkdb;' -U postgres
- psql -d postgres -c "CREATE USER greeklinkuser WITH PASSWORD 'greeklink1'; GRANT
  ALL PRIVILEGES ON DATABASE greeklinkdb TO greeklinkuser; ALTER USER greeklinkuser
  CREATEDB;"
install:
- pip install -r requirements.txt
env:
  matrix:
  - ENV='testing' VERIFY_EMAIL='verify@greek-rho.com' ANN_EMAIL='announcements@greek-rho.com'
    SUPPORT_EMAIL='support@greek-rho.com' EMAIL_HOST_USER='noreply@greek-rho.com'
  global:
  - secure: "KfUbDjYL7yim8h+pqTCuBxM6ZJLZ1rz7ZYKkl4xUnnWvRrP2Fcgch7+xkUQZ+qXrMqT4665LXG+tk7RWoy9bpF+nb0aSvxkAs9CQBdXu7no9tZdggCZMGBEPO6k5Co29P3gwACp4vCrM+cKOFN4zS/p9X1+meWW7WnADUGz1DWGVwcc4SYo0NlRm3P6Qxp7phxgTtyAtA+p6tds1hvooKKdkIld448FYNyJ2S/CjHW0DFAcok11zEgsz24IRjgNHo+Oxt5XhFtN8mqES4Gm/BeeIdRYOZ4Mc7Be9JnjCv1WfA88i6CMwcUbwWZzPWZk+FzKik8MUFR9B0MP+R9agz4ek7JOXKLJcRK5bP3Cr79XSptQ1ip+nzq5wM4W0j1yNCfrUxrBhf7XILCRKlSjhCP7P5E369rWGzk+rIGpdHMSB+UxWG2QngiWFTN+RTR0fW2qVqvf6B7yu2Y7PiFzDrZAy6bri4h+D8wWwQS+t39tuAYCxv89KnlvHBstdtwwzZRewrKsRjQ+J4Qv0D6BsQU33AdvHscpcb2v12xXtsZe3HbnNvCy0hLRHMQ5YyXOuJTYF724f7gnXFzvmTGgQpYa6jPXwkUQPfQvl/9O+hktXgjmnbL+jc04H9aQjD3nyB0R+bQ2OVJqIVMb1uLnW9wvP47IhSEy6KDp7BqJ8spA="
  - secure: IrMoFhvUixZ2qrAdsCqKXqwoKgWbeEAvMTas7LUX5831RjMAog0dW0/C9avKr6I/A+S2oJQJDLclY+oGojrGid29VkjJHtsIC/ewgRQxAP5sSQudZeeFX63WIgoEafkxbhPHlGUr5M7OdoO86db/xE5E92RxMevsm2Kz5JVYYwNwgqF/n4wjPT02H6ny8RhNqVxVPHEjDXPbhK4HkZYRYfxLkzZGv6oHmJOhgrzkVf6swNzv75tCTh+EbmdYtylFbp7KuUMWMnxz8CuVi91Qzc1DlQSF+VjiRgobe6FNN14ddxj8KIbmWB63tzMe8M0dzoqXjxmgc/pso3Ok4DS9Z8MAyvAEEGCjfMBLFWS8hQPisoqJbuKRXMPMRbrD+4MqY3xwBrYqq93lxlNfqkZ5mKBUlyfEJpn0vlqSjcWYUJI2QyyjaRRL/RR2dne0Ra7sQIdHvH+NdL75szZk0WyyOIP6qJec/dZCedF2T/gucU3gOcEX3UHo3eC9xmJ4XXMsb16QUlCQyLS/BmPjhjD1kFpygeRkEUZkGCpUpuefBAbtJSg5ub17+2aUt4w4IrERx95EIZ2dj9b4a2O8Z5YisSJJIAZbR/szORVmtdvmJwSLwmN7zOZtR49zuIxGNad11qNY6V8j5MKVb8JL/yIShLT+eyOiYy455QoV56Um9Dg=
  - secure: TtsInHG3brrTI4P5EmgJ2+a6eM1BWm8YvqhTiQvtR0HSfY+MSdL7RREnXZoc7vwTIEUD98wbBakOKayekCf5HdlYNuGYRlY0Llh8WPGxt/aZGIEpdAH9oBh5ylEXDslGhGKwIcr+kgwAqddnRzNWLUAJHfbAqzgM7RPNnTkWf1FYUmqFCyT6dg5I9fFi3lA3uy3R8AKbG+htNDym4x4DBySvtHpi+Q4OhVhSmgh8kDMpGpWJk6SYj5DiruwLjPUbknDOIebJY33JNsTjM2UWNTeIpogtSQ3u0NApHZLUSqXUpYzN/THf1/6v+9AvgW/lPGl2T+BJwZNoolY4GSbtMWWI7OOMp0XR/eoU0oEdl/5LS/WMUGkurACV4f7VxL8oZBUaj7EA+hhIfNMJtBy4aQHBB56rPDyZjPs3s7Kyq/G/RBpMcoYgUTXhFc8BQ+hhz9fX+pNlj2Nl7FKSfMFP4ujPVR2oy1A6TCd0qaYr/8ZsZOU7kzobRKK1xpMctV6l2ih1biL0SQMBvx7CZu2BIKHPTP57MfhM1hQgdQBM2BoseK6e/u7v6JcbPO/HeLqDM+Cdi3rt9yI9Xh0gZfBnvF/6bCuhgzJ8rQUyM5k0CE/HI/DrdcOcF6yztU77RpXXhqN0IYixqN3qdbl8hqX6X2FkgLXGA6DoI/kppMLx/IY=
script:
- python manage.py makemigrations core
- python manage.py makemigrations organizations
- python manage.py makemigrations rush
- python manage.py makemigrations cal
- python manage.py makemigrations finance
- python manage.py migrate_schemas
- python manage.py collectstatic
- python manage.py test
