language: python
python:
  - "3.6"
# postgres database
services:
  - postgresql
before_script:
  - psql -c 'create database greeklinkdb;' -U postgres
  - psql -d postgres -c "CREATE USER greeklinkuser WITH PASSWORD 'greeklink1'; GRANT ALL PRIVILEGES ON DATABASE greeklinkdb TO greeklinkuser;"
# command to install dependencies
install:
  - pip install -r requirements.txt
# environment variables
env:
  - ENV='testing' DJANGO_SECRET_KEY='1g5rtg0b+nk3axel583k$2gvfq-9zf-80dg_vuy#=zr$-byem^'
# command to run tests
script:
  - python manage.py makemigrations core
  - python manage.py migrate
  - python manage.py collectstatic
  - python manage.py test