language: python
python:
- '3.6'
services:
- postgresql
before_script:
- psql -c 'create database greeklinkdb;' -U postgres
- psql -d postgres -c "CREATE USER greeklinkuser WITH PASSWORD 'greeklink1'; GRANT
  ALL PRIVILEGES ON DATABASE greeklinkdb TO greeklinkuser; ALTER USER greeklinkuser
  CREATEDB;"
install:
- pip install -r requirements.txt
env:
  matrix:
  - ENV='testing' VERIFY_EMAIL='verify@greek-rho.com' ANN_EMAIL='announcements@greek-rho.com'
    SUPPORT_EMAIL='support@greek-rho.com' EMAIL_HOST_USER='noreply@greek-rho.com'
  global:
  - secure: XU7UZLGFasnuCzoOPMRAMZA9F+A+2ygxKoWzvSYeg6L5Eegi2U5x2m8X+OnC68qBjhaPRH7bZpWyIX9/vcz7e8Bx6R4pbv/USocAhd4BYUoHWE8HXIH6YS6bzG8T+fQeg27hFpA5g3z5v/KlfjxKLi9F8TJImalFyb0cB9gjrOq6n7u6mUWAiUHh/XwWxKLRH/CCBzWDkb4nVGYPgBwU4spmkYgT3zA6tPP6HXWZKohKWxKitdt57hoViI79mSBh0o7qbyqEOB7pCflmLpU4YSr/npi4Td15C1E1AB8vFjbRocwEck7QbUOXnqLibvDqP441aLLcGOqwuuM7QEY/byOL9ZvjbWTGxVFjfaJ7nxpOF6Oxoh3hLK3TJ6/g4LCMJKvleuxx2nc3UdvDCI3dHNcWYdPHDyfbQUChxThjXGtAZBpIgpWqHA0V4q3N3aZGZ+1QuaX04VmLRVl/mXW/3roL4KWX1e4xzWstsMsORjLRUvLAZZAxooQvXzovG15vL1hbdRvXZ36mjcNrbS4MUEVSb1zqkzznHIJxEKz7o488VIwBQ3J8CiwFUDqi0i+0D67JTWrwxvVvqh2U7FfxO/S3t+LKNZ6pbst9tmiXgKzhTU+AKBB5rCvLwbfSYyNhcoPX2ubyJbBWb0vCn1TuiR2svI4FFnav8sQ7EOdPcpg=
  - secure: IrMoFhvUixZ2qrAdsCqKXqwoKgWbeEAvMTas7LUX5831RjMAog0dW0/C9avKr6I/A+S2oJQJDLclY+oGojrGid29VkjJHtsIC/ewgRQxAP5sSQudZeeFX63WIgoEafkxbhPHlGUr5M7OdoO86db/xE5E92RxMevsm2Kz5JVYYwNwgqF/n4wjPT02H6ny8RhNqVxVPHEjDXPbhK4HkZYRYfxLkzZGv6oHmJOhgrzkVf6swNzv75tCTh+EbmdYtylFbp7KuUMWMnxz8CuVi91Qzc1DlQSF+VjiRgobe6FNN14ddxj8KIbmWB63tzMe8M0dzoqXjxmgc/pso3Ok4DS9Z8MAyvAEEGCjfMBLFWS8hQPisoqJbuKRXMPMRbrD+4MqY3xwBrYqq93lxlNfqkZ5mKBUlyfEJpn0vlqSjcWYUJI2QyyjaRRL/RR2dne0Ra7sQIdHvH+NdL75szZk0WyyOIP6qJec/dZCedF2T/gucU3gOcEX3UHo3eC9xmJ4XXMsb16QUlCQyLS/BmPjhjD1kFpygeRkEUZkGCpUpuefBAbtJSg5ub17+2aUt4w4IrERx95EIZ2dj9b4a2O8Z5YisSJJIAZbR/szORVmtdvmJwSLwmN7zOZtR49zuIxGNad11qNY6V8j5MKVb8JL/yIShLT+eyOiYy455QoV56Um9Dg=
  - secure: TtsInHG3brrTI4P5EmgJ2+a6eM1BWm8YvqhTiQvtR0HSfY+MSdL7RREnXZoc7vwTIEUD98wbBakOKayekCf5HdlYNuGYRlY0Llh8WPGxt/aZGIEpdAH9oBh5ylEXDslGhGKwIcr+kgwAqddnRzNWLUAJHfbAqzgM7RPNnTkWf1FYUmqFCyT6dg5I9fFi3lA3uy3R8AKbG+htNDym4x4DBySvtHpi+Q4OhVhSmgh8kDMpGpWJk6SYj5DiruwLjPUbknDOIebJY33JNsTjM2UWNTeIpogtSQ3u0NApHZLUSqXUpYzN/THf1/6v+9AvgW/lPGl2T+BJwZNoolY4GSbtMWWI7OOMp0XR/eoU0oEdl/5LS/WMUGkurACV4f7VxL8oZBUaj7EA+hhIfNMJtBy4aQHBB56rPDyZjPs3s7Kyq/G/RBpMcoYgUTXhFc8BQ+hhz9fX+pNlj2Nl7FKSfMFP4ujPVR2oy1A6TCd0qaYr/8ZsZOU7kzobRKK1xpMctV6l2ih1biL0SQMBvx7CZu2BIKHPTP57MfhM1hQgdQBM2BoseK6e/u7v6JcbPO/HeLqDM+Cdi3rt9yI9Xh0gZfBnvF/6bCuhgzJ8rQUyM5k0CE/HI/DrdcOcF6yztU77RpXXhqN0IYixqN3qdbl8hqX6X2FkgLXGA6DoI/kppMLx/IY=
script:
- python manage.py makemigrations core
- python manage.py makemigrations organizations
- python manage.py makemigrations rush
- python manage.py makemigrations cal
- python manage.py migrate_schemas
- python manage.py collectstatic
- python manage.py test
