language: python
python:
  - "3.6"
# postgres database
services:
  - postgresql
before_script:
  - psql -c 'create database greeklinkdb;' -U postgres
  - psql -d postgres -c "CREATE USER greeklinkuser WITH PASSWORD 'greeklink1'; GRANT ALL PRIVILEGES ON DATABASE greeklinkdb TO greeklinkuser; ALTER USER greeklinkuser CREATEDB;"
# command to install dependencies
install:
  - pip install -r requirements.txt
# environment variables
env:
  - ENV='testing' 
  - DJANGO_SECRET_KEY='1g5rtg0b+nk3axel583k$2gvfq-9zf-80dg_vuy#=zr$-byem^'
  - VERIFY_EMAIL='greekrhoverify@gmail.com'
  - VERIFY_PASSWORD='level99!'
  - ANN_EMAIL='announcementsgreekrho@gmail.com'
  - ANN_PASSWORD='level99!'

# command to run tests
script:
  - python manage.py makemigrations core
  - python manage.py makemigrations organizations
  - python manage.py makemigrations rush
  - python manage.py makemigrations cal
  - python manage.py migrate_schemas
  - python manage.py collectstatic
  - python manage.py test