name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: psycopg2 requisites
      run: sudo apt-get install python-dev libpq-dev
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py makemigrations core
        python manage.py makemigrations organizations
        python manage.py makemigrations rush
        python manage.py makemigrations cal
        python manage.py migrate_schemas
        python manage.py collectstatic
        python manage.py test
      env:
        ENV: testing
        VERIFY_EMAIL: verify@greek-rho.com
        ANN_EMAIL: announcements@greek-rho.com
        SUPPORT_EMAIL: support@greek-rho.com
        EMAIL_HOST_USER: noreply@greek-rho.com
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
